name: happywhale
channels: 
- pytorch
- defaults
- conda-forge
dependencies:
- python=3.9.12
- pip=21.1.3
- pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
- torchvision=0.12.0=py39_cu113
- pip:
  - numpy==1.21.5
  - opencv-python==4.5.5.64
  - timm==0.5.4
  - tqdm==4.64.0
  - pandas==1.4.2
  - sklearn==0.0
  - albumentations==1.1.0